#协及的文件有哪些？
#------------------------------------------------------------------------
#r2122
#改变的路径:
D /trunk/gionee/WBT5500/mediatek/custom/common/cgen/CFG_file_info.c
/trunk/gionee/WBT5500/mediatek/custom/common/kernel/alsps/gn_ltr559_auto/gn_ltr559.c
/trunk/gionee/WBT5500/mediatek/custom/common/kernel/alsps/gn_ltr559_auto/gn_ltr559.h
/trunk/gionee/WBT5500/mediatek/custom/common/kernel/alsps/inc/cust_alsps_ltr559.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/cfgdefault/CFG_PS_CALI_Default.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/cfgfileinc/CFG_PS_Cali_File.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/inc/CFG_file_info_custom.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/inc/Custom_NvRam_LID.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/inc/Custom_NvRam_data_item.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/inc/custom_cfg_module_default.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/cgen/inc/custom_cfg_module_file.h
/trunk/gionee/WBT5500/mediatek/custom/gionee82_wet_jb5/kernel/alsps/gn_ltr559_auto/cust_alsps_ltr559.c
/trunk/gionee/WBT5500/mediatek/kernel/drivers/hwmon/hwmsen/hwmsen_dev.c
/trunk/gionee/WBT5500/mediatek/packages/apps/nvram_backup_binder/Android.mk
/trunk/gionee/WBT5500/mediatek/packages/apps/nvram_backup_binder/nvram_ps_op.cpp
/trunk/gionee/WBT5500/mediatek/packages/apps/nvram_backup_binder/nvram_ps_op.h
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/ft/Android.mk
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/ft/ft_fnc.cpp
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/gionee/Android.mk
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/gionee/meta_gionee.c
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/gionee/meta_gionee.h
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/gionee/meta_gionee_para.h
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/gionee/meta_gionee_test.c
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/include/FT_Cmd_Para.h
/trunk/gionee/WBT5500/mediatek/platform/mt6582/external/meta/include/meta_common.h
CR00924820
优化APS
